FROM alpine

ENV BASE_OS_IMAGE=alpine

COPY . /root/sdist

RUN apk add --no-cache \
        ca-certificates \
        alpine-sdk \
        python-dev \
        py-lxml \
        py-setuptools \
        py-twisted \
        py-pip

RUN cd /root/sdist && \
    pip install -U pip setuptools && \
    python setup.py install && \
    cd /root && \
    rm -rf sdist && \
    apk del --purge \
        alpine-sdk \
        python-dev

ENTRYPOINT ["canari"]