FROM amazonlinux:2017.03.1.20170812

COPY . /root/sdist

RUN sudo yum install -y gcc libxml2-devel libxslt-devel

RUN cd /root/sdist && \
    pip install -U pip setuptools && \
    python setup.py install && \
    cd /root && \
    rm -rf sdist && \
    apk del --purge \
        alpine-sdk \
        python-dev

ENTRYPOINT ["canari"]