FROM ubuntu:17.10

ENV BASE_OS_IMAGE=ubuntu

COPY . /root/sdist

RUN apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -y \
        ca-certificates \
        build-essential \
        python-lxml \
        python-dev \
        python-setuptools \
        python-pip

RUN cd /root/sdist && \
    pip install -U pip setuptools && \
    python setup.py install && \
    cd /root && \
    rm -rf sdist && \
    apt-get purge --auto-remove -y \
        build-essential \
        python-dev && \
    apt-get clean

ENTRYPOINT ["canari"]