FROM alpine:3.7

ENV BASE_OS_IMAGE=alpine

COPY . /root/sdist

RUN apk add --no-cache \
        ca-certificates \
        alpine-sdk \
        python3-dev \
        py3-lxml \
        openssl-dev \
        libffi-dev

RUN cd /root/sdist && \
    python3 setup.py install && \
    cd /root && \
    rm -rf sdist && \
    apk del --purge \
        alpine-sdk \
        python3-dev

ENTRYPOINT ["canari"]