FROM ubuntu:14.04

ENV DOCKER=ubuntu

COPY . /root/sdist

RUN apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -y \
        ca-certificates \
        build-essential \
        python-lxml \
        python-dev \
        python-setuptools && \
    cd /root/sdist && \
    python setup.py install && \
    cd /root && \
    rm -rf sdist && \
    apt-get purge --auto-remove -y \
        build-essential \
        python-dev && \
    apt-get clean

ENTRYPOINT ["canari"]