#!/usr/bin/env python

from canari.mode import set_canari_mode, CanariMode
from canari.commands.common import canari_main
# Do not remove this line. It loads all our sub-commands into the main commander.
# noinspection PyUnresolvedReferences
from canari.commands import *

__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Canari Project'
__credits__ = []

__license__ = 'GPLv3'
__version__ = '0.2'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'

if __name__ == '__main__':
    try:
        set_canari_mode(CanariMode.LocalUnknown)
        canari_main()
    except KeyboardInterrupt:
        print('exiting...')
