#!/usr/bin/env python
import sys
sys.path.insert(0, '')
from canari.commands.run_transform import run_transform
from canari.mode import set_canari_mode, CanariMode

__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Canari Project'
__credits__ = []

__license__ = 'GPLv3'
__version__ = '0.1'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


if __name__ == '__main__':
    set_canari_mode(CanariMode.LocalDispatch)
    run_transform.parser.prog = 'dispatcher'
    opts = run_transform.parser.parse_args()
    run_transform(opts)
